config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # get feeds as root
  root "feeds#index"
  resources :feeds
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :feed

  paginates_per 5
end

app/models/feed.rb
class Feed < ApplicationRecord
  include ActiveModel::Validations
  require 'nokogiri'
  require 'feed_validator'
  require "addressable/uri"

  has_many :contents
  validates_presence_of :title, :url
  validates_uniqueness_of :title, :url, case_sensitive: true
  validate :is_valid_url
  validate :w3c_validate
  validate :is_rss


  # verify if url exist with net/http request
  def is_valid_url
    begin
      require "net/http"
      encoded_url = Addressable::URI.encode(self.url)
      uri = Addressable::URI.parse(encoded_url)
      http = Net::HTTP.new(uri.host, uri.port)
      req = Net::HTTP::Get.new(uri.request_uri)
      res = http.request(req)
      puts res.code
    rescue => e
      # error occured, return false
      false
      errors.add(:url, "n'est pas une adresse existante")
      puts "Exceptions : #{e}"
    end
  end

  # validate atom or rss from w3c validator
  def w3c_validate
    begin
      v = W3C::FeedValidator.new()
      v.validate_url(self.url)
      puts v.to_s unless v.valid?
    rescue => e
      # error occured, return false
      false
      errors.add(:url, "n'est pas un flux rss valide")
      puts "w3c validation errors : #{e}"
    end
  end

  # check if format is xml
  def is_xml
    begin
      xml = Nokogiri::XML(open(self.url).read) do |config|
        config.strict.noblanks
      end
    rescue => e
      errors.add(:url, "n'est pas au format xml")
      p e
    end
  end

  # check if format is xml, rss or atom
  def is_rss
    begin
      xml = Faraday.get(self.url).body
      parsed_feed = Feedjira.parse xml
    rescue => e
      errors.add(:url, "format attendu : rss")
      p e
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  def index
    @feeds = Feed.all
  end

  def new
    @feed = Feed.new
    respond_to do |format|
      format.js
    end
  end

  def create
    @feed = Feed.new(feed_params)
    respond_to do |format|
      if @feed.save
        CreateContentsJob.perform_now(@feed)
        format.js { flash.now[:notice] = 'Le flux RSS a bien été ajouté' }
      else
        format.js
        @feed.errors.any?
        @feed.errors.each do |key, value|
        end
      end
    end
  end

  def update
    @content = Content.find params[:id]
    @content.update(readed: 1)
    respond_to do |format|
      format.js
    end
  end

  def feed_params
    params.require(:feed).permit(:title, :url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper

  def create_contents(feed) 
  end

end

app/views/feeds/_feed.haml
.col-sm-12.col-lg-6
  .card.mb-5
    .card-header
      %h4= feed.title
      %p= link_to feed.url, feed.url
    .card-body
      %ul.list-group
        - contents = feed.contents.order('pub_date DESC').page(params[:page])
        - contents.each do |item|
          %li.list-group-item.mb-3
            %b
              = link_to item.title.truncate(35), item.url,
                                                 id: "title-item-#{item.id}",
                                                 class: "#{item.readed ? 'text-grey' : 'text-black'}"
            .float-right.pub_date= item.pub_date.to_formatted_s(:short)
            %p.description.mt-2.float-left= sanitize strip_links(item.description).gsub(/\n/,"<image/>").html_safe, tags: ['image']
            .float-right
              %div{id: "status-item-#{item.id}"}
                = render 'feed_item_status', item: item
    .card-footer
      = paginate contents

app/views/feeds/_feed_item_status.html.haml
- if item.readed?
  %span= "lu"
- else
  = link_to 'Marquer comme lu', feed_path(item.id),
                                method: :put,
                                remote: true,
                                id: 'read'

app/views/feeds/_new.html.haml
= form_for @feed, role: 'form', class: 'form-inline', remote: true  do |f|

  .row
    .offset-lg-2.col-lg-10
      .panel.panel-default
        .panel-body
          .form-group
            = f.label :title, "Titre"
            = f.text_field :title, class: 'form-control'
          .form-group
            = f.label :url, "URL"
            = f.url_field :url, class: 'form-control'

          .float-right
            = f.submit 'GO', class: 'btn btn-lg btn-primary', id: 'submit_feed'
            %div{id: "feed_form_errors"}

app/views/feeds/create.js.erb
//remove old validation messages
$("#feed_form_errors").empty();

<% if @feed.errors.any? %>
  //display new validation messages
  <% @feed.errors.each do |key, value| %>
    $("#feed_form_errors").append('<div class=”notice”><%= escape_javascript(key)%> <%= escape_javascript(value)%></div>');
  <% end %>
<% else %>
  $("#flash").append('<%= j render partial: "shared/notice_banner" %>');
<% end %>

app/views/feeds/index.haml
.container
  #flash
    - if notice.present?
      = render partial: "shared/notice_banner"

  .row.mb-5.mt-5
    .col-lg-12
      .float-right

        = link_to 'Ajouter un flux', new_feed_url,
                                     remote: true,
                                     id: 'new_feed',
                                     class: 'btn btn-primary'
      #form_feed



  .row
    #render_feed
    - @feeds.each do |feed|
      = render 'feed', feed: feed

app/views/feeds/new.js.erb
$("#form_feed").append("<%= j render(:partial => 'feeds/new') %>");
$("#new_feed").hide();

app/views/feeds/update.js.erb
// render partial status
$('#status-item-<%= @content.id %>').empty();
$('#status-item-<%= @content.id %>').append("<%= j render  'feed_item_status', item: @content %>");
// change title color
$('#title-item-<%= @content.id %>').removeClass('text-black');
$('#title-item-<%= @content.id %>').addClass('text-grey');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rss</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_notice_banner.html.haml
%div{class:"alert alert-success", role:"alert"}
  = notice
  %a.close{:href => "#"} ×